In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]    # data 1,2열은 inputs로, 3열은 outputs로
inputs = inputs.fillna(inputs.mean())    # 결측치 평균값으로 채우기
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [5]:
inputs = pd.get_dummies(inputs, dummy_na=True)    # 가변수로 변환
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [8]:
weekdays = pd.DataFrame({'weekdays':['mon', 'tue', 'wed', 'thurs', 'fri', np.nan]})
pd.get_dummies(weekdays, dummy_na=True)

weekdays_fri  weekdays_mon  weekdays_thurs  weekdays_tue  weekdays_wed  \
0             0             1               0             0             0   
1             0             0               0             1             0   
2             0             0               0             0             1   
3             0             0               1             0             0   
4             1             0               0             0             0   
5             0             0               0             0             0   

   weekdays_nan  
0             0  
1             0  
2             0  
3             0  
4             0  
5             1

In [10]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [17]:
exercises = pd.DataFrame([[1, 2, 3, 4],
                         [np.NaN, 2, 3, 4],
                         [1, 2, 3, 4]])
exercises = exercises.dropna()
exercises

0  1  2  3
0  1.0  2  3  4
2  1.0  2  3  4

In [19]:
ex_torch = torch.tensor(exercises.values)
ex_torch

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.]], dtype=torch.float64)