In [17]:
import torch
# Scalar
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x +y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [18]:
# Vectors
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [19]:
x[3]

tensor(3)

In [20]:
len(x)

4

In [21]:
x.shape

torch.Size([4])

In [22]:
# Matrices
A = torch.arange(20).reshape(5, -1)    # reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [23]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [24]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [25]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [26]:
# Tensors
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [27]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()    # A의 복제를 새로운 메모리에 할당
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [28]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [29]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [30]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [31]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [32]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [33]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [34]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [35]:
A.sum(axis=[0, 1])    # == A.sum()

tensor(190.)

In [37]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [41]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [44]:
sum_A = A.sum(axis=1, keepdims=True)    # dimension 유지
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [45]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [46]:
A.cumsum(axis=0)    # cumulative sum

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [47]:
# Dot Products 스칼라 곱
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [48]:
torch.sum(x * y)    # 와 같음

tensor(6.)

In [49]:
# Matrix-Vector Products
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [51]:
A, B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [50]:
# Matrix-Matrix Multiplication
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [52]:
# Norms
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [53]:
torch.abs(u).sum()

tensor(7.)

In [54]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [59]:
# Exercises 1
A_T = (A.T)
A_T.T == A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [76]:
# Exercises 2
A = torch.arange(20).reshape(5, -1)
B = torch.ones(5, 4)
AplusB = A + B
A_TB_T = A.T + B.T
AplusB.T, A_TB_T

(tensor([[ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.],
         [ 4.,  8., 12., 16., 20.]]), tensor([[ 1.,  5.,  9., 13., 17.],
         [ 2.,  6., 10., 14., 18.],
         [ 3.,  7., 11., 15., 19.],
         [ 4.,  8., 12., 16., 20.]]))

In [77]:
# Exercises 3
A = torch.arange(9).reshape(3, 3)
A + A.T

tensor([[ 0,  4,  8],
        [ 4,  8, 12],
        [ 8, 12, 16]])

In [78]:
# Exercises 4
X = torch.zeros(2, 3, 4)
len(X)
# Exercises 5: first dimension

2

In [79]:
# Exercises 6
A / A.sum(axis=1)

tensor([[0.0000, 0.0833, 0.0952],
        [1.0000, 0.3333, 0.2381],
        [2.0000, 0.5833, 0.3810]])

In [81]:
# Exercises 7
dist_ave = 30.0
dist_str = 40.0
dist = torch.tensor([dist_ave, dist_str])
# L1 norm
L1 = torch.abs(dist).sum()
# L2 norm
L2 = torch.norm(dist)
print(L1, L2)

tensor(70.) tensor(50.)


In [82]:
# Exercises 8
C = torch.arange(24).reshape(2, 3, 4)
C

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [83]:
C.sum(axis=0), C.sum(axis=1), C.sum(axis=2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]), tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]), tensor([[ 6, 22, 38],
         [54, 70, 86]]))