In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad    # default value is None

In [5]:
y = 2 * torch.dot(x, x)   # 2 * (1*1 + 2*2 + 3*3)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [8]:
# PyTorch는 기본적으로 gradient를 축적하기 때문에 초기화해야 함
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [10]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [11]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [12]:
# detaching computation
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [13]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [14]:
from math import e
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

In [15]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [16]:
a.grad == d / a

tensor(True)